FROM node:18-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# Copy the rest of the application
COPY . .

# Disable telemetry during the build
ENV NEXT_TELEMETRY_DISABLED 1

# Show detailed build output
RUN set -x && npm run build

# Set up for production
ENV NODE_ENV production
EXPOSE 3000

CMD ["npm", "start"] 